wp:
  image: library/wordpress:latest
  ports:
   - 80:80
  links:
    - mysql:mysql
mysql:
  image: mysql:latest
  environment:
   - MYSQL_ROOT_PASSWORD=root
  volumes:
    - ./data/mysql:/var/lib/mysql
    - ./log/mysql:/var/log/mysql